<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260628213122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixture ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE fixture ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_5e540ee_fifa_match RENAME TO UNIQ_5E540EE70AADBB5');
        $this->addSql('ALTER TABLE prediction ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE prediction ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE team ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE team ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tournament_group ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tournament_group ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ADD is_active BOOLEAN DEFAULT TRUE NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fixture ALTER id SET DEFAULT nextval(\'fixture_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE fixture ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_5e540ee70aadbb5 RENAME TO uniq_5e540ee_fifa_match');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE prediction ALTER id SET DEFAULT nextval(\'prediction_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE prediction ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE team ALTER id SET DEFAULT nextval(\'team_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE team ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tournament_group ALTER id SET DEFAULT nextval(\'tournament_group_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE tournament_group ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" DROP is_active');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
    }
}
