# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.mailer_from_email: '%env(string:MAILER_FROM_EMAIL)%'
    app.mailer_from_name: '%env(string:MAILER_FROM_NAME)%'
    app.callmebot_phone: '%env(string:CALLMEBOT_PHONE)%'
    app.callmebot_apikey: '%env(string:CALLMEBOT_APIKEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $appEnvironment: '%kernel.environment%'
            Symfony\Component\Mime\Address $mailerFromAddress: '@app.mailer_from_address'

    app.mailer_from_address:
        class: Symfony\Component\Mime\Address
        arguments:
            $address: '%app.mailer_from_email%'
            $name: '%app.mailer_from_name%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\WhatsAppService:
        arguments:
            $phone: '%app.callmebot_phone%'
            $apiKey: '%app.callmebot_apikey%'

